# syntax=docker/dockerfile:1
ARG BASE_FROM
FROM ${BASE_FROM} AS ros

ENV ROS_DISTRO=noetic

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    apt-get update \
    && apt-get install -y \
      ca-certificates \
      curl \
      gnupg2 \
      lsb-release \
    && rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
    && echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list \
    && apt-get update \
    && apt-get install -y \
      ros-noetic-desktop-full \
      build-essential \
      python3-rosdep \
      python3-rosinstall \
      python3-rosinstall-generator \
      python3-wstool \
    && rm -rf /var/lib/apt/lists/*